[device]
backend = "cpu"

[functions.zero_bc]
type = "scalar expression"
expression = "0.0"
variables = ["x", "y", "t"]

[functions.source_func]
type = "vector expression"
expressions = ["2 * pi^2 * sin(2 * pi * x) * sin(2 * pi * y)"]
variables = ["x", "y", "t"]

[mesh]
file_path = "poisson.g"
file_type = "exodus"

[[boundary_conditions.dirichlet]]
function = "zero_bc"
side_sets = ["sset_1", "sset_2"]
variables = ["u"]

[[boundary_conditions.dirichlet]]
function = "zero_bc"
side_sets = ["sset_3", "sset_4"]
variables = ["u"]

[[boundary_conditions.source]]
function = "source_func"
blocks = ["block_1"]
variables = ["u"]

# [linear_solver.krylov]

