[device]
backend = "cpu"

[functions.zero_ic]
type = "constant"
expression = "0.0"
variables = ["x", "y"]

[functions.zero_bc]
type = "constant"
expression = "0.0"
variables = ["x", "y", "t"]

[mesh]
file_path = "poisson.g"
file_type = "exodus"

[[initial_conditions]]
function = "zero_ic"
blocks = ["block_1"]
variables = ["u"]

[[boundary_conditions.dirichlet]]
function = "zero_bc"
side_sets = ["sset_1", "sset_2", "sset_3", "sset_4"]
variables = ["u"]
