[device]
backend = "cpu"

[functions.zero]
type = "constant"
expression = "0.0"
variables = ["x", "y"]

[functions.one]
type = "constant"
expression = "1.0"
variables = ["x", "y"]

[mesh]
file_path = "poisson.g"
file_type = "exodus"

[[initial_conditions]]
function = "one"
block = "block_1"
variable = "u"

[[boundary_conditions.dirichlet]]
function = "zero"
side_set = "sset_1"
variable = "u"
